blueprint:
  name: Advanced Lighting Control with Bedtime, On-Air, and Lux Adaptive Modes
  description: >
    Control a light with different behaviors based on Bedtime Mode, On-Air Mode, and Normal Mode with adaptive lux settings. Customize On-Air pulsing patterns, bedtime schedules, and more.
  domain: automation
  input:
    light_entity:
      name: Light Entity
      description: The light to be controlled by the automation.
      selector:
        entity:
          domain: light

    occupancy_sensor:
      name: Occupancy Sensor
      description: The sensor that detects occupancy to trigger the light.
      selector:
        entity:
          domain: binary_sensor

    lux_sensor:
      name: Lux Sensor
      description: The sensor used to determine the room's brightness.
      selector:
        entity:
          domain: sensor

    bedtime_start:
      name: Bedtime Start Time
      selector:
        time:
    bedtime_end:
      name: Bedtime End Time
      selector:
        time:
    manual_bedtime_duration:
      name: Manual Bedtime Duration
      description: Duration for manually activating Bedtime Mode.
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: minutes
    bedtime_brightness:
      name: Bedtime Mode Brightness
      selector:
        number:
          min: 1
          max: 255
          unit_of_measurement: brightness
    bedtime_color:
      name: Bedtime Mode Color
      description: Default is warm white (255, 172, 42).
      selector:
        color_rgb:
      default: [255, 172, 42]

    on_air_entity:
      name: On-Air Mode Toggle Entity
      description: The entity (boolean) that triggers On-Air Mode.
      selector:
        entity:
          domain: input_boolean

    on_air_color:
      name: On-Air Mode Color
      description: Default is red (255, 34, 0).
      selector:
        color_rgb:
      default: [255, 34, 0]

    on_air_pulse:
      name: On-Air Pulse
      description: Enable the pulsing effect for On-Air Mode.
      selector:
        boolean:

    on_air_pulse_pattern:
      name: On-Air Pulse Pattern
      selector:
        select:
          options:
            - "Sine Wave"
            - "Linear"
            - "Exponential"
            - "Sawtooth"
            - "Triangle"
            - "Ease In-Out"

    pulse_min_brightness:
      name: Pulse Minimum Brightness
      selector:
        number:
          min: 1
          max: 255
          unit_of_measurement: brightness

    pulse_length:
      name: Pulse Length
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: seconds

    lux_threshold:
      name: Lux Threshold for Normal Mode
      selector:
        number:
          min: 0
          max: 400
          unit_of_measurement: lux

    adaptive_brightness:
      name: Enable Adaptive Brightness Based on Lux
      selector:
        boolean:

    min_brightness:
      name: Minimum Brightness
      selector:
        number:
          min: 1
          max: 255
          unit_of_measurement: brightness

    max_brightness:
      name: Maximum Brightness
      selector:
        number:
          min: 1
          max: 255
          unit_of_measurement: brightness

    motion_inactive_delay:
      name: Motion Inactive Turn Off
      description: Time (in seconds) the light stays on after motion stops before dimming.
      selector:
        number:
          min: 1
          max: 300
          unit_of_measurement: seconds

    dimming_time:
      name: Dimming Time
      description: Time (in seconds) it takes for the light to transition from on to off after motion stops.
      selector:
        number:
          min: 1
          max: 20
          unit_of_measurement: seconds

    vacation_mode:
      name: Vacation Mode
      description: Enable Vacation Mode to disable Bedtime and On-Air automations.
      selector:
        entity:
          domain: input_boolean

variables:
  light_entity: !input light_entity
  occupancy_sensor: !input occupancy_sensor
  lux_sensor: !input lux_sensor
  bedtime_start: !input bedtime_start
  bedtime_end: !input bedtime_end
  manual_bedtime_duration: !input manual_bedtime_duration
  bedtime_brightness: !input bedtime_brightness
  bedtime_color: !input bedtime_color
  on_air_entity: !input on_air_entity
  on_air_color: !input on_air_color
  on_air_pulse: !input on_air_pulse
  on_air_pulse_pattern: !input on_air_pulse_pattern
  pulse_min_brightness: !input pulse_min_brightness
  pulse_length: !input pulse_length
  lux_threshold: !input lux_threshold
  adaptive_brightness: !input adaptive_brightness
  min_brightness: !input min_brightness
  max_brightness: !input max_brightness
  motion_inactive_delay: !input motion_inactive_delay
  dimming_time: !input dimming_time
  vacation_mode: !input vacation_mode

trigger:
  - platform: state
    entity_id: !input occupancy_sensor
    to: 'on'

condition:
  - condition: template
    value_template: "{{ not is_state(vacation_mode, 'on') }}"

action:
  - choose:
      - conditions:
          - "{{ is_state(on_air_entity, 'on') }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
            data:
              color_name: "{{ on_air_color }}"
          - choose:
              - conditions:
                  - "{{ on_air_pulse }}"
                sequence:
                  - repeat:
                      count: "{{ pulse_length }}"
                      sequence:
                        - service: light.turn_on
                          target:
                            entity_id: !input light_entity
                          data_template:
                            brightness: >
                              {% if on_air_pulse_pattern == "Sine Wave" %}
                                {{ 127 + 127 * sin(now().timestamp() | float / pulse_length) }}
                              {% elif on_air_pulse_pattern == "Linear" %}
                                {{ (now().timestamp() | float % pulse_length) * 255 / pulse_length }}
                              {% elif on_air_pulse_pattern == "Exponential" %}
                                {{ 255 * (1 - exp(-now().timestamp() / pulse_length)) }}
                              {% elif on_air_pulse_pattern == "Sawtooth" %}
                                {{ (now().timestamp() | float % pulse_length) * 255 / pulse_length }}
                              {% elif on_air_pulse_pattern == "Triangle" %}
                                {{ abs((now().timestamp() | float % pulse_length) * 2 - 255) }}
                              {% elif on_air_pulse_pattern == "Ease In-Out" %}
                                {{ (sin((now().timestamp() | float / pulse_length) * pi) + 1) * 127 }}
                              {% else %}
                                255
                              {% endif %}
                        - delay:
                            seconds: 1

      - conditions:
          - "{{ is_state(vacation_mode, 'on') }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity

      - conditions:
          - "{{ is_state('input_select.light_mode', 'Bedtime') }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
            data:
              brightness: "{{ bedtime_brightness }}"
              rgb_color: "{{ bedtime_color }}"

      - conditions:
          - "{{ is_state('input_select.light_mode', 'Normal') }}"
        sequence:
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: !input lux_sensor
                    below: "{{ lux_threshold | float }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light_entity
                    data_template:
                      brightness: >
                        {% if adaptive_brightness %}
                          {{ min_brightness + ((max_brightness - min_brightness) * (lux_threshold | float - states(lux_sensor) | float) / lux_threshold | float) }}
                        {% else %}
                          255
                        {% endif %}

  - wait_template: "{{ is_state(occupancy_sensor, 'off') }}"
    timeout: "{{ motion_inactive_delay | int }}"

  - service: light.turn_on
    target:
      entity_id: !input light_entity
    data:
      brightness: 1
      transition: "{{ dimming_time }}"

  - delay: "{{ dimming_time }}"

  - service: light.turn_off
    target:
      entity_id: !input light_entity
